// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo-protobuf.proto

package demo.camel;

public final class TransactionProtos {
    private TransactionProtos() {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface TransactionOrBuilder extends
            // @@protoc_insertion_point(interface_extends:demo.camel.Transaction)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string transactionid = 1;</code>
         * 
         * @return The transactionid.
         */
        java.lang.String getTransactionid();

        /**
         * <code>string transactionid = 1;</code>
         * 
         * @return The bytes for transactionid.
         */
        com.google.protobuf.ByteString getTransactionidBytes();

        /**
         * <code>string transactiontype = 2;</code>
         * 
         * @return The transactiontype.
         */
        java.lang.String getTransactiontype();

        /**
         * <code>string transactiontype = 2;</code>
         * 
         * @return The bytes for transactiontype.
         */
        com.google.protobuf.ByteString getTransactiontypeBytes();

        /**
         * <code>.demo.camel.Transaction.User sender = 3;</code>
         * 
         * @return Whether the sender field is set.
         */
        boolean hasSender();

        /**
         * <code>.demo.camel.Transaction.User sender = 3;</code>
         * 
         * @return The sender.
         */
        demo.camel.TransactionProtos.Transaction.User getSender();

        /**
         * <code>.demo.camel.Transaction.User sender = 3;</code>
         */
        demo.camel.TransactionProtos.Transaction.UserOrBuilder getSenderOrBuilder();

        /**
         * <code>string currency = 4;</code>
         * 
         * @return The currency.
         */
        java.lang.String getCurrency();

        /**
         * <code>string currency = 4;</code>
         * 
         * @return The bytes for currency.
         */
        com.google.protobuf.ByteString getCurrencyBytes();

        /**
         * <code>double amt = 5;</code>
         * 
         * @return The amt.
         */
        double getAmt();

        /**
         * <code>string receiverid = 6;</code>
         * 
         * @return The receiverid.
         */
        java.lang.String getReceiverid();

        /**
         * <code>string receiverid = 6;</code>
         * 
         * @return The bytes for receiverid.
         */
        com.google.protobuf.ByteString getReceiveridBytes();
    }

    /**
     * Protobuf type {@code demo.camel.Transaction}
     */
    public static final class Transaction extends com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:demo.camel.Transaction)
            TransactionOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use Transaction.newBuilder() to construct.
        private Transaction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Transaction() {
            transactionid_ = "";
            transactiontype_ = "";
            currency_ = "";
            receiverid_ = "";
        }

        @java.lang.Override
        @SuppressWarnings({ "unused" })
        protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
            return new Transaction();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return this.unknownFields;
        }

        private Transaction(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
                    .newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                    case 0:
                        done = true;
                        break;
                    case 10: {
                        java.lang.String s = input.readStringRequireUtf8();

                        transactionid_ = s;
                        break;
                    }
                    case 18: {
                        java.lang.String s = input.readStringRequireUtf8();

                        transactiontype_ = s;
                        break;
                    }
                    case 26: {
                        demo.camel.TransactionProtos.Transaction.User.Builder subBuilder = null;
                        if (sender_ != null) {
                            subBuilder = sender_.toBuilder();
                        }
                        sender_ = input.readMessage(demo.camel.TransactionProtos.Transaction.User.parser(),
                                extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom(sender_);
                            sender_ = subBuilder.buildPartial();
                        }

                        break;
                    }
                    case 34: {
                        java.lang.String s = input.readStringRequireUtf8();

                        currency_ = s;
                        break;
                    }
                    case 41: {

                        amt_ = input.readDouble();
                        break;
                    }
                    case 50: {
                        java.lang.String s = input.readStringRequireUtf8();

                        receiverid_ = s;
                        break;
                    }
                    default: {
                        if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return demo.camel.TransactionProtos.internal_static_demo_camel_Transaction_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
            return demo.camel.TransactionProtos.internal_static_demo_camel_Transaction_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(demo.camel.TransactionProtos.Transaction.class,
                            demo.camel.TransactionProtos.Transaction.Builder.class);
        }

        public interface UserOrBuilder extends
                // @@protoc_insertion_point(interface_extends:demo.camel.Transaction.User)
                com.google.protobuf.MessageOrBuilder {

            /**
             * <code>string username = 1;</code>
             * 
             * @return The username.
             */
            java.lang.String getUsername();

            /**
             * <code>string username = 1;</code>
             * 
             * @return The bytes for username.
             */
            com.google.protobuf.ByteString getUsernameBytes();

            /**
             * <code>string userid = 2;</code>
             * 
             * @return The userid.
             */
            java.lang.String getUserid();

            /**
             * <code>string userid = 2;</code>
             * 
             * @return The bytes for userid.
             */
            com.google.protobuf.ByteString getUseridBytes();
        }

        /**
         * Protobuf type {@code demo.camel.Transaction.User}
         */
        public static final class User extends com.google.protobuf.GeneratedMessageV3 implements
                // @@protoc_insertion_point(message_implements:demo.camel.Transaction.User)
                UserOrBuilder {
            private static final long serialVersionUID = 0L;

            // Use User.newBuilder() to construct.
            private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
                super(builder);
            }

            private User() {
                username_ = "";
                userid_ = "";
            }

            @java.lang.Override
            @SuppressWarnings({ "unused" })
            protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
                return new User();
            }

            @java.lang.Override
            public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
                return this.unknownFields;
            }

            private User(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                this();
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
                        .newBuilder();
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            java.lang.String s = input.readStringRequireUtf8();

                            username_ = s;
                            break;
                        }
                        case 18: {
                            java.lang.String s = input.readStringRequireUtf8();

                            userid_ = s;
                            break;
                        }
                        default: {
                            if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        }
                    }
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(this);
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
                } finally {
                    this.unknownFields = unknownFields.build();
                    makeExtensionsImmutable();
                }
            }

            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return demo.camel.TransactionProtos.internal_static_demo_camel_Transaction_User_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
                return demo.camel.TransactionProtos.internal_static_demo_camel_Transaction_User_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(demo.camel.TransactionProtos.Transaction.User.class,
                                demo.camel.TransactionProtos.Transaction.User.Builder.class);
            }

            public static final int USERNAME_FIELD_NUMBER = 1;
            private volatile java.lang.Object username_;

            /**
             * <code>string username = 1;</code>
             * 
             * @return The username.
             */
            @java.lang.Override
            public java.lang.String getUsername() {
                java.lang.Object ref = username_;
                if (ref instanceof java.lang.String) {
                    return (java.lang.String) ref;
                } else {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    username_ = s;
                    return s;
                }
            }

            /**
             * <code>string username = 1;</code>
             * 
             * @return The bytes for username.
             */
            @java.lang.Override
            public com.google.protobuf.ByteString getUsernameBytes() {
                java.lang.Object ref = username_;
                if (ref instanceof java.lang.String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                            .copyFromUtf8((java.lang.String) ref);
                    username_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            public static final int USERID_FIELD_NUMBER = 2;
            private volatile java.lang.Object userid_;

            /**
             * <code>string userid = 2;</code>
             * 
             * @return The userid.
             */
            @java.lang.Override
            public java.lang.String getUserid() {
                java.lang.Object ref = userid_;
                if (ref instanceof java.lang.String) {
                    return (java.lang.String) ref;
                } else {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    userid_ = s;
                    return s;
                }
            }

            /**
             * <code>string userid = 2;</code>
             * 
             * @return The bytes for userid.
             */
            @java.lang.Override
            public com.google.protobuf.ByteString getUseridBytes() {
                java.lang.Object ref = userid_;
                if (ref instanceof java.lang.String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                            .copyFromUtf8((java.lang.String) ref);
                    userid_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            private byte memoizedIsInitialized = -1;

            @java.lang.Override
            public final boolean isInitialized() {
                byte isInitialized = memoizedIsInitialized;
                if (isInitialized == 1)
                    return true;
                if (isInitialized == 0)
                    return false;

                memoizedIsInitialized = 1;
                return true;
            }

            @java.lang.Override
            public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
                if (!getUsernameBytes().isEmpty()) {
                    com.google.protobuf.GeneratedMessageV3.writeString(output, 1, username_);
                }
                if (!getUseridBytes().isEmpty()) {
                    com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userid_);
                }
                unknownFields.writeTo(output);
            }

            @java.lang.Override
            public int getSerializedSize() {
                int size = memoizedSize;
                if (size != -1)
                    return size;

                size = 0;
                if (!getUsernameBytes().isEmpty()) {
                    size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, username_);
                }
                if (!getUseridBytes().isEmpty()) {
                    size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userid_);
                }
                size += unknownFields.getSerializedSize();
                memoizedSize = size;
                return size;
            }

            @java.lang.Override
            public boolean equals(final java.lang.Object obj) {
                if (obj == this) {
                    return true;
                }
                if (!(obj instanceof demo.camel.TransactionProtos.Transaction.User)) {
                    return super.equals(obj);
                }
                demo.camel.TransactionProtos.Transaction.User other = (demo.camel.TransactionProtos.Transaction.User) obj;

                if (!getUsername().equals(other.getUsername()))
                    return false;
                if (!getUserid().equals(other.getUserid()))
                    return false;
                if (!unknownFields.equals(other.unknownFields))
                    return false;
                return true;
            }

            @java.lang.Override
            public int hashCode() {
                if (memoizedHashCode != 0) {
                    return memoizedHashCode;
                }
                int hash = 41;
                hash = (19 * hash) + getDescriptor().hashCode();
                hash = (37 * hash) + USERNAME_FIELD_NUMBER;
                hash = (53 * hash) + getUsername().hashCode();
                hash = (37 * hash) + USERID_FIELD_NUMBER;
                hash = (53 * hash) + getUserid().hashCode();
                hash = (29 * hash) + unknownFields.hashCode();
                memoizedHashCode = hash;
                return hash;
            }

            public static demo.camel.TransactionProtos.Transaction.User parseFrom(java.nio.ByteBuffer data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data);
            }

            public static demo.camel.TransactionProtos.Transaction.User parseFrom(java.nio.ByteBuffer data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data, extensionRegistry);
            }

            public static demo.camel.TransactionProtos.Transaction.User parseFrom(com.google.protobuf.ByteString data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data);
            }

            public static demo.camel.TransactionProtos.Transaction.User parseFrom(com.google.protobuf.ByteString data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data, extensionRegistry);
            }

            public static demo.camel.TransactionProtos.Transaction.User parseFrom(byte[] data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data);
            }

            public static demo.camel.TransactionProtos.Transaction.User parseFrom(byte[] data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return PARSER.parseFrom(data, extensionRegistry);
            }

            public static demo.camel.TransactionProtos.Transaction.User parseFrom(java.io.InputStream input)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
            }

            public static demo.camel.TransactionProtos.Transaction.User parseFrom(java.io.InputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
            }

            public static demo.camel.TransactionProtos.Transaction.User parseDelimitedFrom(java.io.InputStream input)
                    throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
            }

            public static demo.camel.TransactionProtos.Transaction.User parseDelimitedFrom(java.io.InputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
                        extensionRegistry);
            }

            public static demo.camel.TransactionProtos.Transaction.User parseFrom(
                    com.google.protobuf.CodedInputStream input) throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
            }

            public static demo.camel.TransactionProtos.Transaction.User parseFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
                return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
            }

            @java.lang.Override
            public Builder newBuilderForType() {
                return newBuilder();
            }

            public static Builder newBuilder() {
                return DEFAULT_INSTANCE.toBuilder();
            }

            public static Builder newBuilder(demo.camel.TransactionProtos.Transaction.User prototype) {
                return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
            }

            @java.lang.Override
            public Builder toBuilder() {
                return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
            }

            @java.lang.Override
            protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                Builder builder = new Builder(parent);
                return builder;
            }

            /**
             * Protobuf type {@code demo.camel.Transaction.User}
             */
            public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                    // @@protoc_insertion_point(builder_implements:demo.camel.Transaction.User)
                    demo.camel.TransactionProtos.Transaction.UserOrBuilder {
                public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                    return demo.camel.TransactionProtos.internal_static_demo_camel_Transaction_User_descriptor;
                }

                @java.lang.Override
                protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
                    return demo.camel.TransactionProtos.internal_static_demo_camel_Transaction_User_fieldAccessorTable
                            .ensureFieldAccessorsInitialized(demo.camel.TransactionProtos.Transaction.User.class,
                                    demo.camel.TransactionProtos.Transaction.User.Builder.class);
                }

                // Construct using demo.camel.TransactionProtos.Transaction.User.newBuilder()
                private Builder() {
                    maybeForceBuilderInitialization();
                }

                private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                    super(parent);
                    maybeForceBuilderInitialization();
                }

                private void maybeForceBuilderInitialization() {
                    if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
                    }
                }

                @java.lang.Override
                public Builder clear() {
                    super.clear();
                    username_ = "";

                    userid_ = "";

                    return this;
                }

                @java.lang.Override
                public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                    return demo.camel.TransactionProtos.internal_static_demo_camel_Transaction_User_descriptor;
                }

                @java.lang.Override
                public demo.camel.TransactionProtos.Transaction.User getDefaultInstanceForType() {
                    return demo.camel.TransactionProtos.Transaction.User.getDefaultInstance();
                }

                @java.lang.Override
                public demo.camel.TransactionProtos.Transaction.User build() {
                    demo.camel.TransactionProtos.Transaction.User result = buildPartial();
                    if (!result.isInitialized()) {
                        throw newUninitializedMessageException(result);
                    }
                    return result;
                }

                @java.lang.Override
                public demo.camel.TransactionProtos.Transaction.User buildPartial() {
                    demo.camel.TransactionProtos.Transaction.User result = new demo.camel.TransactionProtos.Transaction.User(
                            this);
                    result.username_ = username_;
                    result.userid_ = userid_;
                    onBuilt();
                    return result;
                }

                @java.lang.Override
                public Builder clone() {
                    return super.clone();
                }

                @java.lang.Override
                public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
                    return super.setField(field, value);
                }

                @java.lang.Override
                public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
                    return super.clearField(field);
                }

                @java.lang.Override
                public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                    return super.clearOneof(oneof);
                }

                @java.lang.Override
                public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
                        java.lang.Object value) {
                    return super.setRepeatedField(field, index, value);
                }

                @java.lang.Override
                public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
                        java.lang.Object value) {
                    return super.addRepeatedField(field, value);
                }

                @java.lang.Override
                public Builder mergeFrom(com.google.protobuf.Message other) {
                    if (other instanceof demo.camel.TransactionProtos.Transaction.User) {
                        return mergeFrom((demo.camel.TransactionProtos.Transaction.User) other);
                    } else {
                        super.mergeFrom(other);
                        return this;
                    }
                }

                public Builder mergeFrom(demo.camel.TransactionProtos.Transaction.User other) {
                    if (other == demo.camel.TransactionProtos.Transaction.User.getDefaultInstance())
                        return this;
                    if (!other.getUsername().isEmpty()) {
                        username_ = other.username_;
                        onChanged();
                    }
                    if (!other.getUserid().isEmpty()) {
                        userid_ = other.userid_;
                        onChanged();
                    }
                    this.mergeUnknownFields(other.unknownFields);
                    onChanged();
                    return this;
                }

                @java.lang.Override
                public final boolean isInitialized() {
                    return true;
                }

                @java.lang.Override
                public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
                    demo.camel.TransactionProtos.Transaction.User parsedMessage = null;
                    try {
                        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                        parsedMessage = (demo.camel.TransactionProtos.Transaction.User) e.getUnfinishedMessage();
                        throw e.unwrapIOException();
                    } finally {
                        if (parsedMessage != null) {
                            mergeFrom(parsedMessage);
                        }
                    }
                    return this;
                }

                private java.lang.Object username_ = "";

                /**
                 * <code>string username = 1;</code>
                 * 
                 * @return The username.
                 */
                public java.lang.String getUsername() {
                    java.lang.Object ref = username_;
                    if (!(ref instanceof java.lang.String)) {
                        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                        java.lang.String s = bs.toStringUtf8();
                        username_ = s;
                        return s;
                    } else {
                        return (java.lang.String) ref;
                    }
                }

                /**
                 * <code>string username = 1;</code>
                 * 
                 * @return The bytes for username.
                 */
                public com.google.protobuf.ByteString getUsernameBytes() {
                    java.lang.Object ref = username_;
                    if (ref instanceof String) {
                        com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                                .copyFromUtf8((java.lang.String) ref);
                        username_ = b;
                        return b;
                    } else {
                        return (com.google.protobuf.ByteString) ref;
                    }
                }

                /**
                 * <code>string username = 1;</code>
                 * 
                 * @param value
                 *            The username to set.
                 * 
                 * @return This builder for chaining.
                 */
                public Builder setUsername(java.lang.String value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }

                    username_ = value;
                    onChanged();
                    return this;
                }

                /**
                 * <code>string username = 1;</code>
                 * 
                 * @return This builder for chaining.
                 */
                public Builder clearUsername() {

                    username_ = getDefaultInstance().getUsername();
                    onChanged();
                    return this;
                }

                /**
                 * <code>string username = 1;</code>
                 * 
                 * @param value
                 *            The bytes for username to set.
                 * 
                 * @return This builder for chaining.
                 */
                public Builder setUsernameBytes(com.google.protobuf.ByteString value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    checkByteStringIsUtf8(value);

                    username_ = value;
                    onChanged();
                    return this;
                }

                private java.lang.Object userid_ = "";

                /**
                 * <code>string userid = 2;</code>
                 * 
                 * @return The userid.
                 */
                public java.lang.String getUserid() {
                    java.lang.Object ref = userid_;
                    if (!(ref instanceof java.lang.String)) {
                        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                        java.lang.String s = bs.toStringUtf8();
                        userid_ = s;
                        return s;
                    } else {
                        return (java.lang.String) ref;
                    }
                }

                /**
                 * <code>string userid = 2;</code>
                 * 
                 * @return The bytes for userid.
                 */
                public com.google.protobuf.ByteString getUseridBytes() {
                    java.lang.Object ref = userid_;
                    if (ref instanceof String) {
                        com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                                .copyFromUtf8((java.lang.String) ref);
                        userid_ = b;
                        return b;
                    } else {
                        return (com.google.protobuf.ByteString) ref;
                    }
                }

                /**
                 * <code>string userid = 2;</code>
                 * 
                 * @param value
                 *            The userid to set.
                 * 
                 * @return This builder for chaining.
                 */
                public Builder setUserid(java.lang.String value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }

                    userid_ = value;
                    onChanged();
                    return this;
                }

                /**
                 * <code>string userid = 2;</code>
                 * 
                 * @return This builder for chaining.
                 */
                public Builder clearUserid() {

                    userid_ = getDefaultInstance().getUserid();
                    onChanged();
                    return this;
                }

                /**
                 * <code>string userid = 2;</code>
                 * 
                 * @param value
                 *            The bytes for userid to set.
                 * 
                 * @return This builder for chaining.
                 */
                public Builder setUseridBytes(com.google.protobuf.ByteString value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    checkByteStringIsUtf8(value);

                    userid_ = value;
                    onChanged();
                    return this;
                }

                @java.lang.Override
                public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                    return super.setUnknownFields(unknownFields);
                }

                @java.lang.Override
                public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                    return super.mergeUnknownFields(unknownFields);
                }

                // @@protoc_insertion_point(builder_scope:demo.camel.Transaction.User)
            }

            // @@protoc_insertion_point(class_scope:demo.camel.Transaction.User)
            private static final demo.camel.TransactionProtos.Transaction.User DEFAULT_INSTANCE;
            static {
                DEFAULT_INSTANCE = new demo.camel.TransactionProtos.Transaction.User();
            }

            public static demo.camel.TransactionProtos.Transaction.User getDefaultInstance() {
                return DEFAULT_INSTANCE;
            }

            private static final com.google.protobuf.Parser<User> PARSER = new com.google.protobuf.AbstractParser<User>() {
                @java.lang.Override
                public User parsePartialFrom(com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
                    return new User(input, extensionRegistry);
                }
            };

            public static com.google.protobuf.Parser<User> parser() {
                return PARSER;
            }

            @java.lang.Override
            public com.google.protobuf.Parser<User> getParserForType() {
                return PARSER;
            }

            @java.lang.Override
            public demo.camel.TransactionProtos.Transaction.User getDefaultInstanceForType() {
                return DEFAULT_INSTANCE;
            }

        }

        public static final int TRANSACTIONID_FIELD_NUMBER = 1;
        private volatile java.lang.Object transactionid_;

        /**
         * <code>string transactionid = 1;</code>
         * 
         * @return The transactionid.
         */
        @java.lang.Override
        public java.lang.String getTransactionid() {
            java.lang.Object ref = transactionid_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                transactionid_ = s;
                return s;
            }
        }

        /**
         * <code>string transactionid = 1;</code>
         * 
         * @return The bytes for transactionid.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getTransactionidBytes() {
            java.lang.Object ref = transactionid_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                transactionid_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int TRANSACTIONTYPE_FIELD_NUMBER = 2;
        private volatile java.lang.Object transactiontype_;

        /**
         * <code>string transactiontype = 2;</code>
         * 
         * @return The transactiontype.
         */
        @java.lang.Override
        public java.lang.String getTransactiontype() {
            java.lang.Object ref = transactiontype_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                transactiontype_ = s;
                return s;
            }
        }

        /**
         * <code>string transactiontype = 2;</code>
         * 
         * @return The bytes for transactiontype.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getTransactiontypeBytes() {
            java.lang.Object ref = transactiontype_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                transactiontype_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int SENDER_FIELD_NUMBER = 3;
        private demo.camel.TransactionProtos.Transaction.User sender_;

        /**
         * <code>.demo.camel.Transaction.User sender = 3;</code>
         * 
         * @return Whether the sender field is set.
         */
        @java.lang.Override
        public boolean hasSender() {
            return sender_ != null;
        }

        /**
         * <code>.demo.camel.Transaction.User sender = 3;</code>
         * 
         * @return The sender.
         */
        @java.lang.Override
        public demo.camel.TransactionProtos.Transaction.User getSender() {
            return sender_ == null ? demo.camel.TransactionProtos.Transaction.User.getDefaultInstance() : sender_;
        }

        /**
         * <code>.demo.camel.Transaction.User sender = 3;</code>
         */
        @java.lang.Override
        public demo.camel.TransactionProtos.Transaction.UserOrBuilder getSenderOrBuilder() {
            return getSender();
        }

        public static final int CURRENCY_FIELD_NUMBER = 4;
        private volatile java.lang.Object currency_;

        /**
         * <code>string currency = 4;</code>
         * 
         * @return The currency.
         */
        @java.lang.Override
        public java.lang.String getCurrency() {
            java.lang.Object ref = currency_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                currency_ = s;
                return s;
            }
        }

        /**
         * <code>string currency = 4;</code>
         * 
         * @return The bytes for currency.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getCurrencyBytes() {
            java.lang.Object ref = currency_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                currency_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int AMT_FIELD_NUMBER = 5;
        private double amt_;

        /**
         * <code>double amt = 5;</code>
         * 
         * @return The amt.
         */
        @java.lang.Override
        public double getAmt() {
            return amt_;
        }

        public static final int RECEIVERID_FIELD_NUMBER = 6;
        private volatile java.lang.Object receiverid_;

        /**
         * <code>string receiverid = 6;</code>
         * 
         * @return The receiverid.
         */
        @java.lang.Override
        public java.lang.String getReceiverid() {
            java.lang.Object ref = receiverid_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                receiverid_ = s;
                return s;
            }
        }

        /**
         * <code>string receiverid = 6;</code>
         * 
         * @return The bytes for receiverid.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getReceiveridBytes() {
            java.lang.Object ref = receiverid_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                receiverid_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1)
                return true;
            if (isInitialized == 0)
                return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            if (!getTransactionidBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, transactionid_);
            }
            if (!getTransactiontypeBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, transactiontype_);
            }
            if (sender_ != null) {
                output.writeMessage(3, getSender());
            }
            if (!getCurrencyBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 4, currency_);
            }
            if (amt_ != 0D) {
                output.writeDouble(5, amt_);
            }
            if (!getReceiveridBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 6, receiverid_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1)
                return size;

            size = 0;
            if (!getTransactionidBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, transactionid_);
            }
            if (!getTransactiontypeBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, transactiontype_);
            }
            if (sender_ != null) {
                size += com.google.protobuf.CodedOutputStream.computeMessageSize(3, getSender());
            }
            if (!getCurrencyBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, currency_);
            }
            if (amt_ != 0D) {
                size += com.google.protobuf.CodedOutputStream.computeDoubleSize(5, amt_);
            }
            if (!getReceiveridBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, receiverid_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof demo.camel.TransactionProtos.Transaction)) {
                return super.equals(obj);
            }
            demo.camel.TransactionProtos.Transaction other = (demo.camel.TransactionProtos.Transaction) obj;

            if (!getTransactionid().equals(other.getTransactionid()))
                return false;
            if (!getTransactiontype().equals(other.getTransactiontype()))
                return false;
            if (hasSender() != other.hasSender())
                return false;
            if (hasSender()) {
                if (!getSender().equals(other.getSender()))
                    return false;
            }
            if (!getCurrency().equals(other.getCurrency()))
                return false;
            if (java.lang.Double.doubleToLongBits(getAmt()) != java.lang.Double.doubleToLongBits(other.getAmt()))
                return false;
            if (!getReceiverid().equals(other.getReceiverid()))
                return false;
            if (!unknownFields.equals(other.unknownFields))
                return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + TRANSACTIONID_FIELD_NUMBER;
            hash = (53 * hash) + getTransactionid().hashCode();
            hash = (37 * hash) + TRANSACTIONTYPE_FIELD_NUMBER;
            hash = (53 * hash) + getTransactiontype().hashCode();
            if (hasSender()) {
                hash = (37 * hash) + SENDER_FIELD_NUMBER;
                hash = (53 * hash) + getSender().hashCode();
            }
            hash = (37 * hash) + CURRENCY_FIELD_NUMBER;
            hash = (53 * hash) + getCurrency().hashCode();
            hash = (37 * hash) + AMT_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(java.lang.Double.doubleToLongBits(getAmt()));
            hash = (37 * hash) + RECEIVERID_FIELD_NUMBER;
            hash = (53 * hash) + getReceiverid().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static demo.camel.TransactionProtos.Transaction parseFrom(java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static demo.camel.TransactionProtos.Transaction parseFrom(java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static demo.camel.TransactionProtos.Transaction parseFrom(com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static demo.camel.TransactionProtos.Transaction parseFrom(com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static demo.camel.TransactionProtos.Transaction parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static demo.camel.TransactionProtos.Transaction parseFrom(byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static demo.camel.TransactionProtos.Transaction parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static demo.camel.TransactionProtos.Transaction parseFrom(java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static demo.camel.TransactionProtos.Transaction parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
        }

        public static demo.camel.TransactionProtos.Transaction parseDelimitedFrom(java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
                    extensionRegistry);
        }

        public static demo.camel.TransactionProtos.Transaction parseFrom(com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
        }

        public static demo.camel.TransactionProtos.Transaction parseFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(demo.camel.TransactionProtos.Transaction prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code demo.camel.Transaction}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:demo.camel.Transaction)
                demo.camel.TransactionProtos.TransactionOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return demo.camel.TransactionProtos.internal_static_demo_camel_Transaction_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
                return demo.camel.TransactionProtos.internal_static_demo_camel_Transaction_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(demo.camel.TransactionProtos.Transaction.class,
                                demo.camel.TransactionProtos.Transaction.Builder.class);
            }

            // Construct using demo.camel.TransactionProtos.Transaction.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                transactionid_ = "";

                transactiontype_ = "";

                if (senderBuilder_ == null) {
                    sender_ = null;
                } else {
                    sender_ = null;
                    senderBuilder_ = null;
                }
                currency_ = "";

                amt_ = 0D;

                receiverid_ = "";

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return demo.camel.TransactionProtos.internal_static_demo_camel_Transaction_descriptor;
            }

            @java.lang.Override
            public demo.camel.TransactionProtos.Transaction getDefaultInstanceForType() {
                return demo.camel.TransactionProtos.Transaction.getDefaultInstance();
            }

            @java.lang.Override
            public demo.camel.TransactionProtos.Transaction build() {
                demo.camel.TransactionProtos.Transaction result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public demo.camel.TransactionProtos.Transaction buildPartial() {
                demo.camel.TransactionProtos.Transaction result = new demo.camel.TransactionProtos.Transaction(this);
                result.transactionid_ = transactionid_;
                result.transactiontype_ = transactiontype_;
                if (senderBuilder_ == null) {
                    result.sender_ = sender_;
                } else {
                    result.sender_ = senderBuilder_.build();
                }
                result.currency_ = currency_;
                result.amt_ = amt_;
                result.receiverid_ = receiverid_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
                    java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof demo.camel.TransactionProtos.Transaction) {
                    return mergeFrom((demo.camel.TransactionProtos.Transaction) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(demo.camel.TransactionProtos.Transaction other) {
                if (other == demo.camel.TransactionProtos.Transaction.getDefaultInstance())
                    return this;
                if (!other.getTransactionid().isEmpty()) {
                    transactionid_ = other.transactionid_;
                    onChanged();
                }
                if (!other.getTransactiontype().isEmpty()) {
                    transactiontype_ = other.transactiontype_;
                    onChanged();
                }
                if (other.hasSender()) {
                    mergeSender(other.getSender());
                }
                if (!other.getCurrency().isEmpty()) {
                    currency_ = other.currency_;
                    onChanged();
                }
                if (other.getAmt() != 0D) {
                    setAmt(other.getAmt());
                }
                if (!other.getReceiverid().isEmpty()) {
                    receiverid_ = other.receiverid_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
                demo.camel.TransactionProtos.Transaction parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (demo.camel.TransactionProtos.Transaction) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private java.lang.Object transactionid_ = "";

            /**
             * <code>string transactionid = 1;</code>
             * 
             * @return The transactionid.
             */
            public java.lang.String getTransactionid() {
                java.lang.Object ref = transactionid_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    transactionid_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string transactionid = 1;</code>
             * 
             * @return The bytes for transactionid.
             */
            public com.google.protobuf.ByteString getTransactionidBytes() {
                java.lang.Object ref = transactionid_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                            .copyFromUtf8((java.lang.String) ref);
                    transactionid_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string transactionid = 1;</code>
             * 
             * @param value
             *            The transactionid to set.
             * 
             * @return This builder for chaining.
             */
            public Builder setTransactionid(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                transactionid_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string transactionid = 1;</code>
             * 
             * @return This builder for chaining.
             */
            public Builder clearTransactionid() {

                transactionid_ = getDefaultInstance().getTransactionid();
                onChanged();
                return this;
            }

            /**
             * <code>string transactionid = 1;</code>
             * 
             * @param value
             *            The bytes for transactionid to set.
             * 
             * @return This builder for chaining.
             */
            public Builder setTransactionidBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                transactionid_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object transactiontype_ = "";

            /**
             * <code>string transactiontype = 2;</code>
             * 
             * @return The transactiontype.
             */
            public java.lang.String getTransactiontype() {
                java.lang.Object ref = transactiontype_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    transactiontype_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string transactiontype = 2;</code>
             * 
             * @return The bytes for transactiontype.
             */
            public com.google.protobuf.ByteString getTransactiontypeBytes() {
                java.lang.Object ref = transactiontype_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                            .copyFromUtf8((java.lang.String) ref);
                    transactiontype_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string transactiontype = 2;</code>
             * 
             * @param value
             *            The transactiontype to set.
             * 
             * @return This builder for chaining.
             */
            public Builder setTransactiontype(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                transactiontype_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string transactiontype = 2;</code>
             * 
             * @return This builder for chaining.
             */
            public Builder clearTransactiontype() {

                transactiontype_ = getDefaultInstance().getTransactiontype();
                onChanged();
                return this;
            }

            /**
             * <code>string transactiontype = 2;</code>
             * 
             * @param value
             *            The bytes for transactiontype to set.
             * 
             * @return This builder for chaining.
             */
            public Builder setTransactiontypeBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                transactiontype_ = value;
                onChanged();
                return this;
            }

            private demo.camel.TransactionProtos.Transaction.User sender_;
            private com.google.protobuf.SingleFieldBuilderV3<demo.camel.TransactionProtos.Transaction.User, demo.camel.TransactionProtos.Transaction.User.Builder, demo.camel.TransactionProtos.Transaction.UserOrBuilder> senderBuilder_;

            /**
             * <code>.demo.camel.Transaction.User sender = 3;</code>
             * 
             * @return Whether the sender field is set.
             */
            public boolean hasSender() {
                return senderBuilder_ != null || sender_ != null;
            }

            /**
             * <code>.demo.camel.Transaction.User sender = 3;</code>
             * 
             * @return The sender.
             */
            public demo.camel.TransactionProtos.Transaction.User getSender() {
                if (senderBuilder_ == null) {
                    return sender_ == null ? demo.camel.TransactionProtos.Transaction.User.getDefaultInstance()
                            : sender_;
                } else {
                    return senderBuilder_.getMessage();
                }
            }

            /**
             * <code>.demo.camel.Transaction.User sender = 3;</code>
             */
            public Builder setSender(demo.camel.TransactionProtos.Transaction.User value) {
                if (senderBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    sender_ = value;
                    onChanged();
                } else {
                    senderBuilder_.setMessage(value);
                }

                return this;
            }

            /**
             * <code>.demo.camel.Transaction.User sender = 3;</code>
             */
            public Builder setSender(demo.camel.TransactionProtos.Transaction.User.Builder builderForValue) {
                if (senderBuilder_ == null) {
                    sender_ = builderForValue.build();
                    onChanged();
                } else {
                    senderBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }

            /**
             * <code>.demo.camel.Transaction.User sender = 3;</code>
             */
            public Builder mergeSender(demo.camel.TransactionProtos.Transaction.User value) {
                if (senderBuilder_ == null) {
                    if (sender_ != null) {
                        sender_ = demo.camel.TransactionProtos.Transaction.User.newBuilder(sender_).mergeFrom(value)
                                .buildPartial();
                    } else {
                        sender_ = value;
                    }
                    onChanged();
                } else {
                    senderBuilder_.mergeFrom(value);
                }

                return this;
            }

            /**
             * <code>.demo.camel.Transaction.User sender = 3;</code>
             */
            public Builder clearSender() {
                if (senderBuilder_ == null) {
                    sender_ = null;
                    onChanged();
                } else {
                    sender_ = null;
                    senderBuilder_ = null;
                }

                return this;
            }

            /**
             * <code>.demo.camel.Transaction.User sender = 3;</code>
             */
            public demo.camel.TransactionProtos.Transaction.User.Builder getSenderBuilder() {

                onChanged();
                return getSenderFieldBuilder().getBuilder();
            }

            /**
             * <code>.demo.camel.Transaction.User sender = 3;</code>
             */
            public demo.camel.TransactionProtos.Transaction.UserOrBuilder getSenderOrBuilder() {
                if (senderBuilder_ != null) {
                    return senderBuilder_.getMessageOrBuilder();
                } else {
                    return sender_ == null ? demo.camel.TransactionProtos.Transaction.User.getDefaultInstance()
                            : sender_;
                }
            }

            /**
             * <code>.demo.camel.Transaction.User sender = 3;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<demo.camel.TransactionProtos.Transaction.User, demo.camel.TransactionProtos.Transaction.User.Builder, demo.camel.TransactionProtos.Transaction.UserOrBuilder> getSenderFieldBuilder() {
                if (senderBuilder_ == null) {
                    senderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<demo.camel.TransactionProtos.Transaction.User, demo.camel.TransactionProtos.Transaction.User.Builder, demo.camel.TransactionProtos.Transaction.UserOrBuilder>(
                            getSender(), getParentForChildren(), isClean());
                    sender_ = null;
                }
                return senderBuilder_;
            }

            private java.lang.Object currency_ = "";

            /**
             * <code>string currency = 4;</code>
             * 
             * @return The currency.
             */
            public java.lang.String getCurrency() {
                java.lang.Object ref = currency_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    currency_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string currency = 4;</code>
             * 
             * @return The bytes for currency.
             */
            public com.google.protobuf.ByteString getCurrencyBytes() {
                java.lang.Object ref = currency_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                            .copyFromUtf8((java.lang.String) ref);
                    currency_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string currency = 4;</code>
             * 
             * @param value
             *            The currency to set.
             * 
             * @return This builder for chaining.
             */
            public Builder setCurrency(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                currency_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string currency = 4;</code>
             * 
             * @return This builder for chaining.
             */
            public Builder clearCurrency() {

                currency_ = getDefaultInstance().getCurrency();
                onChanged();
                return this;
            }

            /**
             * <code>string currency = 4;</code>
             * 
             * @param value
             *            The bytes for currency to set.
             * 
             * @return This builder for chaining.
             */
            public Builder setCurrencyBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                currency_ = value;
                onChanged();
                return this;
            }

            private double amt_;

            /**
             * <code>double amt = 5;</code>
             * 
             * @return The amt.
             */
            @java.lang.Override
            public double getAmt() {
                return amt_;
            }

            /**
             * <code>double amt = 5;</code>
             * 
             * @param value
             *            The amt to set.
             * 
             * @return This builder for chaining.
             */
            public Builder setAmt(double value) {

                amt_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>double amt = 5;</code>
             * 
             * @return This builder for chaining.
             */
            public Builder clearAmt() {

                amt_ = 0D;
                onChanged();
                return this;
            }

            private java.lang.Object receiverid_ = "";

            /**
             * <code>string receiverid = 6;</code>
             * 
             * @return The receiverid.
             */
            public java.lang.String getReceiverid() {
                java.lang.Object ref = receiverid_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    receiverid_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string receiverid = 6;</code>
             * 
             * @return The bytes for receiverid.
             */
            public com.google.protobuf.ByteString getReceiveridBytes() {
                java.lang.Object ref = receiverid_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                            .copyFromUtf8((java.lang.String) ref);
                    receiverid_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string receiverid = 6;</code>
             * 
             * @param value
             *            The receiverid to set.
             * 
             * @return This builder for chaining.
             */
            public Builder setReceiverid(java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                receiverid_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string receiverid = 6;</code>
             * 
             * @return This builder for chaining.
             */
            public Builder clearReceiverid() {

                receiverid_ = getDefaultInstance().getReceiverid();
                onChanged();
                return this;
            }

            /**
             * <code>string receiverid = 6;</code>
             * 
             * @param value
             *            The bytes for receiverid to set.
             * 
             * @return This builder for chaining.
             */
            public Builder setReceiveridBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                receiverid_ = value;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }

            // @@protoc_insertion_point(builder_scope:demo.camel.Transaction)
        }

        // @@protoc_insertion_point(class_scope:demo.camel.Transaction)
        private static final demo.camel.TransactionProtos.Transaction DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new demo.camel.TransactionProtos.Transaction();
        }

        public static demo.camel.TransactionProtos.Transaction getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Transaction> PARSER = new com.google.protobuf.AbstractParser<Transaction>() {
            @java.lang.Override
            public Transaction parsePartialFrom(com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Transaction(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Transaction> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Transaction> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public demo.camel.TransactionProtos.Transaction getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor internal_static_demo_camel_Transaction_descriptor;
    private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_demo_camel_Transaction_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor internal_static_demo_camel_Transaction_User_descriptor;
    private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_demo_camel_Transaction_User_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
    static {
        java.lang.String[] descriptorData = { "\n\023demo-protobuf.proto\022\ndemo.camel\"\310\001\n\013Tr"
                + "ansaction\022\025\n\rtransactionid\030\001 \001(\t\022\027\n\017tran"
                + "sactiontype\030\002 \001(\t\022,\n\006sender\030\003 \001(\0132\034.demo"
                + ".camel.Transaction.User\022\020\n\010currency\030\004 \001("
                + "\t\022\013\n\003amt\030\005 \001(\001\022\022\n\nreceiverid\030\006 \001(\t\032(\n\004Us"
                + "er\022\020\n\010username\030\001 \001(\t\022\016\n\006userid\030\002 \001(\tB\037\n\n"
                + "demo.camelB\021TransactionProtosb\006proto3" };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
                new com.google.protobuf.Descriptors.FileDescriptor[] {});
        internal_static_demo_camel_Transaction_descriptor = getDescriptor().getMessageTypes().get(0);
        internal_static_demo_camel_Transaction_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_demo_camel_Transaction_descriptor, new java.lang.String[] { "Transactionid",
                        "Transactiontype", "Sender", "Currency", "Amt", "Receiverid", });
        internal_static_demo_camel_Transaction_User_descriptor = internal_static_demo_camel_Transaction_descriptor
                .getNestedTypes().get(0);
        internal_static_demo_camel_Transaction_User_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_demo_camel_Transaction_User_descriptor,
                new java.lang.String[] { "Username", "Userid", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
